language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed ttranphuc99/udagram-api-feed:v3
  - docker tag udagram-api-user ttranphuc99/udagram-api-user:v3
  - docker tag udagram-frontend ttranphuc99/udagram-frontend:v4
  - docker tag reverseproxy ttranphuc99/udagram-reverseproxy:v5

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ttranphuc99/udagram-api-feed:v3
  - docker push ttranphuc99/udagram-api-user:v3
  - docker push ttranphuc99/udagram-frontend:v4
  - docker push ttranphuc99/udagram-reverseproxy:v5
